package com.gto.registrylib;

import com.gto.registrylib.annotations.StandardAPI;
import com.gto.registrylib.builders.BlockBuilder;
import com.gto.registrylib.builders.BlockEntityBuilder;
import com.gto.registrylib.builders.FluidBuilder;
import com.gto.registrylib.builders.ItemBuilder;
import com.gto.registrylib.providers.RegistryLibLangProvider;
import com.gto.registrylib.util.FunctionUtil;

import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.neoforged.neoforge.fluids.BaseFlowingFluid;

import java.util.function.Function;
import java.util.function.UnaryOperator;

import javax.annotation.Nullable;

/**
 * A lightweight grouping wrapper around {@link RegistryCore} that applies shared defaults (creative
 * tab, property modifiers, lang prefix) to all entries created through it.
 *
 * <p>
 * The group name is used to automatically derive a {@code langPrefix}: {@code "machines"}
 * becomes {@code "Machines"}, which is prepended to every entry's display name. You can override
 * this with an explicit {@link Builder#langPrefix(String)} call.
 *
 * <p>
 * {@link Builder#tab(ResourceKey)} applies to <em>all</em> item-like sub-resources: standalone
 * items, block items generated by {@code .simpleItem()}/{@code .item()}, and fluid buckets.
 *
 * <p>
 * Construct via {@link RegistryCore#group(String)}:
 *
 * <pre>{@code
 * 
 * Group MACHINES = REGISTRYLIB.group("machines")  // langPrefix "Machines" auto-derived
 *         .tab(MACHINE_TAB)                       // applied to Item, BlockItem, and Bucket
 *         .blockProperties(p -> p.strength(3.5F))
 *         .build();
 *
 * BlockEntry<Block> CRUSHER = MACHINES.block("crusher", Block::new)
 *         .simpleItem()
 *         .register();
 * }</pre>
 */
public class Group {

    protected final RegistryCore core;
    @Nullable
    protected final ResourceKey<CreativeModeTab> tab;
    @Nullable
    protected final String langPrefix;
    protected final UnaryOperator<BlockBehaviour.Properties> blockPropertiesModifier;
    protected final UnaryOperator<Item.Properties> itemPropertiesModifier;

    protected Group(Builder builder) {
        this.core = builder.core;
        this.tab = builder.tab;
        this.langPrefix = builder.langPrefix;
        this.blockPropertiesModifier = builder.blockPropertiesModifier;
        this.itemPropertiesModifier = builder.itemPropertiesModifier;
    }

    // === Accessors ===

    public RegistryCore getRegistryLib() {
        return core;
    }

    // === Factory Methods ===

    @StandardAPI("Returns a BlockBuilder with group defaults applied. Call .register() to finalise.")
    public <T extends Block> BlockBuilder<T, Group> block(
                                                          String name, Function<BlockBehaviour.Properties, T> factory) {
        return applyBlockDefaults(core.block(this, name, factory));
    }

    public <T extends Item> ItemBuilder<T, Group> item(
                                                       String name, Function<Item.Properties, T> factory) {
        return applyItemDefaults(core.item(this, name, factory, false));
    }

    @StandardAPI("Returns an ItemBuilder with group defaults applied. Call .register() to finalise.")
    public <T extends Item> ItemBuilder<T, Group> item(
                                                       String name, Function<Item.Properties, T> factory, boolean isComponentItem) {
        return applyItemDefaults(core.item(this, name, factory, isComponentItem));
    }

    @StandardAPI("Returns a BlockEntityBuilder with group defaults applied. Call .register() to finalise.")
    public <T extends BlockEntity> BlockEntityBuilder<T, Group> blockEntity(
                                                                            String name, BlockEntityBuilder.BlockEntityFactory<T> factory) {
        return core.blockEntity(this, name, factory);
    }

    @StandardAPI("Returns a FluidBuilder with group defaults applied. Call .register() to finalise.")
    public FluidBuilder<BaseFlowingFluid.Flowing, Group> fluid(
                                                               String name, Identifier stillTexture, Identifier flowingTexture) {
        return applyFluidDefaults(
                core.fluid(this, name, stillTexture, flowingTexture, BaseFlowingFluid.Flowing::new));
    }

    @StandardAPI("Returns a FluidBuilder with custom FluidFactory and group defaults applied. Call .register() to finalise.")
    public <T extends BaseFlowingFluid> FluidBuilder<T, Group> fluid(
                                                                     String name,
                                                                     Identifier stillTexture,
                                                                     Identifier flowingTexture,
                                                                     FluidBuilder.FluidFactory<T> fluidFactory) {
        return applyFluidDefaults(core.fluid(this, name, stillTexture, flowingTexture, fluidFactory));
    }

    // === Default Application ===

    private <T extends Block> BlockBuilder<T, Group> applyBlockDefaults(
                                                                        BlockBuilder<T, Group> builder) {
        var b = builder.properties(blockPropertiesModifier);
        if (tab != null) {
            b = b.defaultItemTab(tab);
        }
        if (langPrefix != null) {
            b = b.lang(langPrefix + " " + RegistryLibLangProvider.toEnglishName(builder.getName()));
        }
        return b;
    }

    private <T extends Item> ItemBuilder<T, Group> applyItemDefaults(ItemBuilder<T, Group> builder) {
        var b = builder.properties(itemPropertiesModifier);
        if (tab != null) {
            b = b.addTab(tab);
        }
        if (langPrefix != null) {
            b = b.lang(langPrefix + " " + RegistryLibLangProvider.toEnglishName(builder.getName()));
        }
        return b;
    }

    private <T extends BaseFlowingFluid> FluidBuilder<T, Group> applyFluidDefaults(
                                                                                   FluidBuilder<T, Group> builder) {
        if (tab != null) {
            builder = builder.defaultBucketTab(tab);
        }
        if (langPrefix != null) {
            builder = builder.lang(langPrefix + " " + RegistryLibLangProvider.toEnglishName(builder.getName()));
        }
        return builder;
    }

    // === Builder ===

    public static class Builder {

        protected final RegistryCore core;
        @Nullable
        protected ResourceKey<CreativeModeTab> tab;
        @Nullable
        protected String langPrefix;
        protected UnaryOperator<BlockBehaviour.Properties> blockPropertiesModifier = FunctionUtil.identityUnaryOp();
        protected UnaryOperator<Item.Properties> itemPropertiesModifier = FunctionUtil.identityUnaryOp();

        protected Builder(RegistryCore core, String name) {
            this.core = core;
            this.langPrefix = core.doDatagen() ? RegistryLibLangProvider.toEnglishName(name) : null;
        }

        /**
         * Sets the creative tab for all item-like entries in this group (items, block items, buckets).
         */
        @StandardAPI
        public Builder tab(ResourceKey<CreativeModeTab> tab) {
            this.tab = tab;
            return this;
        }

        /**
         * Overrides the lang prefix auto-derived from the group name. By default, the group name is
         * converted to title case and used as the prefix (e.g. {@code "machines"} → {@code
         * "Machines"}).
         */
        @StandardAPI
        public Builder langPrefix(String prefix) {
            if (core.doDatagen()) {
                this.langPrefix = prefix;
            }
            return this;
        }

        @StandardAPI
        public Builder blockProperties(UnaryOperator<BlockBehaviour.Properties> modifier) {
            this.blockPropertiesModifier = modifier;
            return this;
        }

        @StandardAPI
        public Builder itemProperties(UnaryOperator<Item.Properties> modifier) {
            this.itemPropertiesModifier = modifier;
            return this;
        }

        @StandardAPI
        public Group build() {
            return new Group(this);
        }
    }
}
